//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvcproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.customers = new HashSet<customer>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string Color { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Product_Description { get; set; }
        public Nullable<int> UnitPrice { get; set; }
        public string Size { get; set; }
    
        public virtual ICollection<customer> customers { get; set; }
    }
}
